version: '3.7'
services:
  jcarpizo_env:
    container_name: jcarpizo_nginx
    image: nginx:latest
    ports:
      - '3687:80'
    volumes:
      -  .:/code
      -  ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - mysql
      - php

  php:
    container_name: jcarpizo_php
    build: .
    volumes:
      -  .:/code
    links:
      - mysql

  phpmyadmin:
    container_name: jcarpizo_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '3684:80'
    links:
      - mysql
    environment:
      PMA_HOST: mysql

  mysql:
    container_name: jcarpizo_mysql
    image: mysql:8.0.16
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_DATABASE: jcarpizo
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - '4567:3306'
    volumes:
      - ./database/dbdata:/var/lib/mysql
